const PDFDocument = require('pdfkit');

/**
 * PDF Service for generating professional travel itinerary PDFs
 */
class PDFService {
  constructor() {
    this.currentPage = 1;
  }

  /**
   * Creates a PDF document and returns a stream
   * @param {Object} itinerary - The itinerary data
   * @returns {PDFKit.PDFDocument} PDF document stream
   */
  createItineraryPDF(itinerary) {
    console.log('[PDFService] Creating PDF');
    this.currentPage = 1;

    const doc = new PDFDocument({ margin: 50 });

    // Set default styles
    doc.font('Helvetica').fontSize(12).fillColor('#333333');

    // Handle page breaks and add footers
    let isFirstPage = true;
   

    // Add footer to first page after writing title to avoid overlap
    this.writeTitle(doc);

    // Write all itinerary sections
    this.writeTripSummary(doc, itinerary.tripSummary);
    this.writeDestinationOverview(doc, itinerary.destinationOverview);
    this.writeWeatherGuide(doc, itinerary.weatherGuide);
    this.writeDailyPlan(doc, itinerary.dailyPlan);
    this.writeBudgetBreakdown(doc, itinerary.budgetBreakdown);
    this.writeAccommodationSuggestions(doc, itinerary.accommodationSuggestions);
    this.writeTransportationPlan(doc, itinerary.transportationPlan);
    this.writeFoodRecommendations(doc, itinerary.foodRecommendations);
    this.writePackingChecklist(doc, itinerary.packingChecklist);
    this.writeClothingRecommendations(doc, itinerary.clothingRecommendations);
    this.writePhotoSpots(doc, itinerary.photoSpots);
    this.writeHiddenGems(doc, itinerary.hiddenGems);
    this.writeBulletList(doc, 'Travel Tips', itinerary.travelTips);
    this.writeBulletList(doc, 'Safety Tips', itinerary.safetyTips);
    this.writeEmergencyInformation(doc, itinerary.emergencyInformation);

    console.log('[PDFService] PDF completed');
    doc.end();
    return doc;
  }

  /**
   * Adds footer to current page
   * @param {PDFKit.PDFDocument} doc
   */
  addFooter(doc) {
    // const { left, bottom } = doc.page.margins;
    // const pageWidth = doc.page.width - left * 2;
    // const savedY = doc.y;
    // const savedFont = doc._font;
    // const savedFontSize = doc._fontSize;
    // const savedFillColor = doc._fillColor;

    // doc
    //   .fontSize(10)
    //   .fillColor('#777777')
    //   .text('Generated by TripMind AI', left, doc.page.height - bottom, { align: 'left' })
    //   .text(`Page ${this.currentPage}`, left, doc.page.height - bottom, {
    //     align: 'right',
    //     width: pageWidth
    //   });

    // doc.y = savedY;
    // doc._font = savedFont;
    // doc._fontSize = savedFontSize;
    // doc._fillColor = savedFillColor;
  }

  /**
   * Writes the PDF title
   * @param {PDFKit.PDFDocument} doc
   */
  writeTitle(doc) {
    doc.moveDown(1);
    doc
      .fontSize(22)
      .font('Helvetica-Bold')
      .fillColor('#111827')
      .text('TripMind AI', { align: 'center' });
    doc
      .fontSize(16)
      .text('AI Travel Itinerary', { align: 'center' });
    doc.font('Helvetica').fontSize(12).fillColor('#333333');
    doc.moveDown(1.5);
  }

  /**
   * Writes a section heading
   * @param {PDFKit.PDFDocument} doc
   * @param {string} title
   */
  writeHeading(doc, title) {
    doc
      .fontSize(14)
      .font('Helvetica-Bold')
      .fillColor('#111827')
      .text(title, { underline: true });
    doc.moveDown(0.5);
    doc.font('Helvetica').fontSize(12).fillColor('#333333');
  }

  /**
   * Writes trip summary
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} tripSummary
   */
  writeTripSummary(doc, tripSummary) {
    this.writeHeading(doc, 'Trip Summary');
    doc.text(`Destination: ${tripSummary.destination}`);
    doc.text(`Dates: ${tripSummary.startDate} - ${tripSummary.endDate}`);
    doc.text(`Duration: ${tripSummary.duration} days`);
    doc.text(`Travelers: ${tripSummary.travelers}`);
    doc.text(`Budget: ${tripSummary.budgetTier}`);
    doc.text(`Travel Style: ${tripSummary.travelStyle}`);
    doc.moveDown(0.5);
    doc.text(`Overall Description: ${tripSummary.overallDescription}`);
    doc.moveDown(1);
  }

  /**
   * Writes destination overview
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} overview
   */
  writeDestinationOverview(doc, overview) {
    this.writeHeading(doc, 'Destination Overview');
    doc.text(`Description: ${overview.description}`);
    doc.moveDown(0.3);
    doc.text(`Best Time to Visit: ${overview.bestTimeToVisit}`);
    doc.moveDown(0.3);
    doc.text(`Local Customs: ${overview.localCustoms}`);
    doc.moveDown(1);
  }

  /**
   * Writes weather guide
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} weatherGuide
   */
  writeWeatherGuide(doc, weatherGuide) {
    this.writeHeading(doc, 'Weather Guide');
    doc.text(`Typical Weather: ${weatherGuide.typicalWeather}`);
    doc.moveDown(0.3);
    doc.text(`Temperature Range: ${weatherGuide.temperatureRange}`);
    doc.moveDown(0.3);
    doc.text(`Precipitation: ${weatherGuide.precipitation}`);
    doc.moveDown(0.3);
    doc.text(`Advice: ${weatherGuide.advice}`);
    doc.moveDown(1);
  }

  /**
   * Writes daily plan
   * @param {PDFKit.PDFDocument} doc
   * @param {Array} dailyPlan
   */
  writeDailyPlan(doc, dailyPlan) {
    this.writeHeading(doc, 'Daily Itinerary');
    dailyPlan.forEach((day) => {
      doc.moveDown(0.3);
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(`Day ${day.day}: ${day.date}`);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');

      // Morning
      doc.fontSize(12).font('Helvetica-Bold').text('Morning');
      doc.font('Helvetica').text(`Activity: ${day.morning.activity}`);
      doc.text(`Location: ${day.morning.location}`);
      doc.moveDown(0.2);

      // Afternoon
      doc.font('Helvetica-Bold').text('Afternoon');
      doc.font('Helvetica').text(`Activity: ${day.afternoon.activity}`);
      doc.text(`Location: ${day.afternoon.location}`);
      doc.moveDown(0.2);

      // Evening
      doc.font('Helvetica-Bold').text('Evening');
      doc.font('Helvetica').text(`Activity: ${day.evening.activity}`);
      doc.text(`Location: ${day.evening.location}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);
  }

  /**
   * Writes budget breakdown
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} budget
   */
  writeBudgetBreakdown(doc, budget) {
    this.writeHeading(doc, 'Budget Breakdown');
    doc
      .fontSize(13)
      .font('Helvetica-Bold')
      .fillColor('#10b981')
      .text(`Total: ${budget.totalEstimate}`);
    doc.font('Helvetica').fontSize(12).fillColor('#333333');
    doc.moveDown(0.2);
    doc.text(`Accommodation: ${budget.accommodation}`);
    doc.text(`Food: ${budget.food}`);
    doc.text(`Transportation: ${budget.transportation}`);
    doc.text(`Activities: ${budget.activities}`);
    doc.text(`Miscellaneous: ${budget.miscellaneous}`);
    doc.moveDown(1);
  }

  /**
   * Writes accommodation suggestions
   * @param {PDFKit.PDFDocument} doc
   * @param {Array} accommodations
   */
  writeAccommodationSuggestions(doc, accommodations) {
    this.writeHeading(doc, 'Accommodation Suggestions');
    accommodations.forEach((acc) => {
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(acc.name);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');
      doc.text(`Location: ${acc.location}`);
      doc.text(`Type: ${acc.type}`);
      doc.text(`Price Range: ${acc.priceRange}`);
      doc.text(`Description: ${acc.description}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);
  }

  /**
   * Writes transportation plan
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} transportation
   */
  writeTransportationPlan(doc, transportation) {
    this.writeHeading(doc, 'Transportation Plan');
    doc.text(`Arrival: ${transportation.arrival}`);
    doc.moveDown(0.3);
    doc.text(`Getting Around: ${transportation.gettingAround}`);
    doc.moveDown(0.3);
    doc.text(`Departure: ${transportation.departure}`);
    doc.moveDown(1);
  }

  /**
   * Writes food recommendations
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} food
   */
  writeFoodRecommendations(doc, food) {
    this.writeHeading(doc, 'Food Recommendations');
    doc.text('Must Try Foods:');
    food.mustTry.forEach((item) => {
      doc.text(`- ${item}`);
    });
    doc.moveDown(0.5);
    food.restaurants.forEach((restaurant) => {
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(restaurant.name);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');
      doc.text(`Cuisine: ${restaurant.cuisine}`);
      doc.text(`Location: ${restaurant.location}`);
      doc.text(`Price: ${restaurant.priceRange}`);
      doc.text(`Description: ${restaurant.description}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);
  }

  /**
   * Writes packing checklist
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} checklist
   */
  writePackingChecklist(doc, checklist) {
    this.writeHeading(doc, 'Packing Checklist');
    const categories = [
      { name: 'Clothing', items: checklist.clothing },
      { name: 'Toiletries', items: checklist.toiletries },
      { name: 'Electronics', items: checklist.electronics },
      { name: 'Documents', items: checklist.documents },
      { name: 'Miscellaneous', items: checklist.miscellaneous }
    ];
    categories.forEach((category) => {
      doc.moveDown(0.2);
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(category.name);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');
      category.items.forEach((item) => {
        doc.text(`- ${item}`);
      });
      doc.moveDown(0.2);
    });
    doc.moveDown(1);
  }

  /**
   * Writes clothing recommendations
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} clothing
   */
  writeClothingRecommendations(doc, clothing) {
    this.writeHeading(doc, 'Clothing Recommendations');
    doc.text(`Daywear: ${clothing.daywear}`);
    doc.moveDown(0.3);
    doc.text(`Eveningwear: ${clothing.eveningwear}`);
    doc.moveDown(0.3);
    doc.text(`Footwear: ${clothing.footwear}`);
    doc.moveDown(1);
  }

  /**
   * Writes photo spots
   * @param {PDFKit.PDFDocument} doc
   * @param {Array} spots
   */
  writePhotoSpots(doc, spots) {
    this.writeHeading(doc, 'Photo Spots');
    spots.forEach((spot) => {
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(spot.name);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');
      doc.text(`Location: ${spot.location}`);
      doc.text(`Best Time: ${spot.bestTime}`);
      doc.text(`Description: ${spot.description}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);
  }

  /**
   * Writes hidden gems
   * @param {PDFKit.PDFDocument} doc
   * @param {Array} gems
   */
  writeHiddenGems(doc, gems) {
    this.writeHeading(doc, 'Hidden Gems');
    gems.forEach((gem) => {
      doc
        .fontSize(13)
        .font('Helvetica-Bold')
        .fillColor('#111827')
        .text(gem.name);
      doc.font('Helvetica').fontSize(12).fillColor('#333333');
      doc.text(`Location: ${gem.location}`);
      doc.text(`Description: ${gem.description}`);
      doc.moveDown(0.5);
    });
    doc.moveDown(1);
  }

  /**
   * Writes a bullet list
   * @param {PDFKit.PDFDocument} doc
   * @param {string} title
   * @param {Array} items
   */
  writeBulletList(doc, title, items) {
    this.writeHeading(doc, title);
    items.forEach((item) => {
      doc.text(`- ${item}`);
    });
    doc.moveDown(1);
  }

  /**
   * Writes emergency information
   * @param {PDFKit.PDFDocument} doc
   * @param {Object} emergencyInfo
   */
  writeEmergencyInformation(doc, emergencyInfo) {
    this.writeHeading(doc, 'Emergency Information');
    doc.text(`Police: ${emergencyInfo.police}`);
    doc.text(`Ambulance: ${emergencyInfo.ambulance}`);
    doc.text(`Fire: ${emergencyInfo.fire}`);
    doc.text(`Embassy: ${emergencyInfo.embassy}`);
    doc.text('Local Emergency Contacts:');
    emergencyInfo.localEmergencyContacts.forEach((contact) => {
      doc.text(`- ${contact}`);
    });
  }

  /**
   * Generates a dynamic filename
   * @param {Object} itinerary
   * @returns {string} Filename
   */
  generateFilename(itinerary) {
    const sanitizedDest = itinerary.tripSummary.destination.replace(/[^a-zA-Z0-9]/g, '-');
    return `TripMind-${sanitizedDest}-${itinerary.tripSummary.startDate}.pdf`;
  }
}

module.exports = new PDFService();
